/* INVOICES */
export const GET_INVOICES = "GET_INVOICES"
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS"
export const GET_INVOICES_FAIL = "GET_INVOICES_FAIL"

export const GET_INVOICE_DETAIL = "GET_INVOICE_DETAIL"
export const GET_INVOICE_DETAIL_SUCCESS = "GET_INVOICE_DETAIL_SUCCESS"
export const GET_INVOICE_DETAIL_FAIL = "GET_INVOICE_DETAIL_FAIL"

export const GET_INVOICE_HISTORY_BYID = 'GET_INVOICE_HISTORY_BYID'
export const GET_INVOICE_HISTORY_BYID_SUCCESS = 'GET_INVOICE_HISTORY_BYID_SUCCESS'

export const GET_INVOICE_HISTORY = 'GET_INVOICE_HISTORY'
export const GET_INVOICE_HISTORY_SUCCESS = 'GET_INVOICE_HISTORY_SUCCESS'

export const GET_INVOICE_HISTORY_BY_COMPANYID_SUCCESS = 'GET_INVOICE_HISTORY_BY_COMPANYID_SUCCESS'
export const GET_INVOICE_HISTORY_BY_COMPANYID = 'GET_INVOICE_HISTORY_BY_COMPANYID'

export const GET_INVOICE_HISTORY_BY_PROJECTID = 'GET_INVOICE_HISTORY_BY_PROJECTID'
export const GET_INVOICE_HISTORY_BY_PROJECTID_SUCCESS = 'GET_INVOICE_HISTORY_BY_PROJECTID_SUCCESS'
