
export const GET_REPORT_HISTORY = "GET_REPORT_HISTORY"
export const GET_REPORT_HISTORY_SUCCESS = 'GET_REPORT_HISTORY_SUCCESS'

export const GET_REPORT_HISTORY_BYPROJECTID = 'GET_REPORT_HISTORY_BYPROJECTID'
export const GET_REPORT_HISTORY_BYPROJECTID_SUCCESS = 'GET_REPORT_HISTORY_BYPROJECTID_SUCCESS'

export const GET_REPORT_HISTORY_BYCOMPANY = 'GET_REPORT_HISTORY_BYCOMPANY'
export const GET_REPORT_HISTORY_BYCOMPANY_SUCCESS = 'GET_REPORT_HISTORY_BYCOMPANY_SUCCESS'

export const GET_REPORT_HISTORY_BYID = 'GET_REPORT_HISTORY_BYID'
export const GET_REPORT_HISTORY_BYID_SUCCESS = 'GET_REPORT_HISTORY_BYID_SUCCESS'
